version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    container_name: previewer-app
    ports:
      - "8090:8090"
    networks:
      - test-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    container_name: previewer-web-nginx
    volumes:
      - shared_volume:/usr/share/nginx/html/images
    ports:
      - "3080:3080"
    networks:
      - test-network

  int-tests:
    build:
      context: .
      dockerfile: Dockerfile_tests
    container_name: int-tests
    volumes:
      - shared_volume:/int_test/test_files
    networks:
      - test-network
    depends_on:
      - app
      - nginx



networks:
  test-network:

volumes:
  shared_volume:
