version: '3.8'

services:
  # Сервис приложения
  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    container_name: previewer-app
    ports:
      - "8090:8090"
    networks:
      - test-network

  # Сервис Nginx
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    container_name: previewer-web-nginx
    volumes:
      - shared_volume:/usr/share/nginx/html/images
    ports:
      - "3080:3080"
    networks:
      - test-network

  # Сервис для интеграционных тестов
  int-tests:
    build:
      context: .
      dockerfile: Dockerfile_tests
    container_name: int-tests
    volumes:
      - shared_volume:/int_test/test_files
    networks:
      - test-network
    depends_on:
      - app  # Зависимость от сервиса приложения
      - nginx # Зависимость от сервиса Nginx
    command: ["tail", "-f", "/dev/null"] # Команда для удержания контейнера в активном состоянии

# Определение общей сети для всех сервисов
networks:
  test-network:

# Определение общего тома для обмена данными между сервисами
volumes:
  shared_volume:
