# Используем официальный образ Go
FROM golang:1.22

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем go.mod и go.sum
COPY go.mod ./
COPY go.sum ./

# Устанавливаем зависимости
RUN go mod download

# Копируем все файлы в контейнер
COPY . .

# Устанавливаем рабочую директорию для тестов
WORKDIR /app/int_test

# Запускаем тесты
CMD ["go", "test", "-v", "./..."]
