version: '3.8'

services:
  app:
    build:
      context: .
    container_name: previewer-app
    ports:
      - "8090:8090"
    networks:
      - test-network

  nginx:
    image: nginx:latest
    container_name: previewer-web-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./int_test/test_files:/usr/share/nginx/html/images
    ports:
      - "3080:3080"
    networks:
      - test-network

networks:
  test-network:
