server:
  http:
    host: 0.0.0.0 # Адрес, на котором сервер будет слушать входящие запросы
    port: 8090    # Порт, на котором сервер будет слушать входящие запросы
    timeout: 10s  # Таймаут для HTTP-запросов
logger:
  level: DEBUG    # Уровень логирования (DEBUG, INFO, WARNING, ERROR)
cache:
  capacity: 10    # Вместимость кеша (максимальное количество объектов в кеше)
storage:
  path: "./images/" # Путь к директории для хранения кешированных изображений
service:
  size: 2048      # Максимальный размер файла в Кб
