name: lint_test_build

on:
  push:
    branches:
      - '*'

jobs:
  run_lint:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Check out code
        uses: actions/checkout@main

      - name: Linters
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2


  run_tests:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: make test


  run_int_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Run integration tests
        run: |
          docker-compose -f docker-compose.yml up -d int-tests
          docker-compose -f docker-compose.yml exec -T int-tests go test ./... -v
          docker-compose -f docker-compose.yml down
          docker volume rm $(docker volume ls -qf dangling=true)

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: make build

