name: lint_test_build

on:
  push:
    branches:
      - '*'

jobs:
  run_lint:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Check out code
        uses: actions/checkout@main

      - name: Linters
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2


  run_tests:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: go test -race -count 100 ./...


  build:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Check out code
        uses: actions/checkout@v3



      - name: Build
        run: make build

